### ISSUE TITLE
Would it be possible to add example run commands in readme?

### ISSUE THREAD

**Issue by pksorensen** [Pointscene/docker-lastools#1]
I am unsure which commands from the toolbox that can be run.

Also for which one require a license.

**Comment by davijo** [comment]
Hi @pksorensen , this container has only the open source versions listed on https://github.com/LAStools/LAStools:
open source tools:

* laszip.exe compresses the LAS files in a completely lossless manner
* lasinfo.exe prints out a quick overview of the contents of a LAS file
* lasindex.exe creates a spatial index LAX file for fast spatial queries
* las2las.exe extracts last returns, clips, subsamples, translates, etc ...
* lasmerge.exe merges several LAS or LAZ files into a single LAS or LAZ file
* txt2las.exe converts LIDAR data from ASCII text to binary LAS format
* las2txt.exe turns LAS into human-readable and easy-to-parse ASCII
* lasprecision.exe analyses the actual precision of the LIDAR points

These are LGPL 2.1 as shown here https://github.com/LAStools/LAStools/blob/master/LICENSE.txt

**Comment by pksorensen** [comment]
Thanks for finding the info for me :) I googled but got confused.

**Comment by davijo** [comment]
Great to hear if others find this useful!

Updated readme 3e2f498e00304370403f29726e8cb57ba8024541
